### ISSUE TITLE
Missing Deepl auth key.

### ISSUE THREAD

**Issue by andreasba** [tobiasfabian/kirby-machine-translation#1]
Good evening Tobias

first of all huge thanks for this great plugin! I am almost embarrased to post this because it seems very obvious that the issue is in front of the computer, not the plugin. But still :) When I:

- Download the repository and save the content to site/plugins/machine-translation
- Add the section as per the readme to a blueprint
- Add the api key into my config.php as in 

![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/19f341d9-11e8-422e-843f-ef392f9f6118)

- and then press the "Translate Page" button in the Panel, I receive the error "Missing Deepl auth key":
- 
![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/e6b5c586-1dd7-4d72-89cb-478ef1003620)

I am running Kirby v4 alpha 5.

Any idea what I am doing wrong?

Thanks
Andreas

**Comment by andreasba** [comment]
For testing purposes, I hardcoded the API key now into the index.php of the plugin. When pressing the button, I now receive a different error message:

![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/1579a3ef-1618-4468-a574-b8da53f7c21f)

Any way how I can help debug this @tobiasfabian ?

Thanks
Andreas

**Comment by tobiasfabian** [comment]
Hi @andreasba,
thanks for testing the plugin. There was indeed a problem with the handling of the options. I fixed it with 160bf70.

You should now be able to set the DeepL key as described in the Readme. I’m not sure about the second error you mentioned. If it still exists, could you please check the Web Inspector console for further details on the error.

**Comment by andreasba** [comment]
Thanks for your quick response @tobiasfabian :)

Now, when pressing the translation button, I get a Fatal DeepL API error:

![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/c81c4783-3b42-46d9-9c66-2f2158ed46d0)

I am not a pro in debugging, but this is what the Web Inspector spits out:

![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/b80678c3-90c5-442c-bfe2-eefa29cd8861)

![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/f4bfb389-693c-4147-be54-f517e22ff1bd)

Is that useful?

**Comment by tobiasfabian** [comment]
Thanks for your reply and thank you for being an early adopter. It helps a lot.

It’s a PHP error which is logged into the JavaScript console. So your second screenshot is the relevant one. It says, that the problem is on line `253` of the file `/site/plugins/machine-translation/lib/Translate.php`. 

https://github.com/tobiasfabian/kirby-machine-translation/blob/160bf7025069e105004ae6cd31f3d14d36e3ccc4/lib/Translate.php#L250-L254

The response of the DeepL API is not as excepted. Therefore I have improved the error handling of the DeepL API response. Could you please [download the latest version](https://github.com/tobiasfabian/kirby-machine-translation/archive/refs/heads/main.zip) and test again?

**Comment by andreasba** [comment]
Thanks for your quick reaction @tobiasfabian ! Your plugin could be extremely useful so it is my pleasure to help anyway I can :) Now I receive the following error code:
![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/6c415f90-1727-4270-9b79-7bdede2080d7)
(and I am quite sure I have the config.php edited in the right way)

If I hardcode the API key again into index.php of the plugin I get the same error. The same when I try via env.php file:

![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/60cdefad-856b-4657-b79a-d17e2483ee31)

Edit: on the DeepL website, it states to make sure to use the right domain: [api-free.deepl.com](https://www.deepl.com/docs-api) (I have a free API key, not a paid one). Could that be the issue?

**Comment by tobiasfabian** [comment]
There is something wrong with your Auth Key. I’m using the free API myself. This should not be the issue.

To debug your issue, could you please check the following. Add a `var_dump($authKey)` between line 239 and 241 of [`lib/Translate.php`](https://github.com/tobiasfabian/kirby-machine-translation/blob/d131a65edf0b6824ecf0da8f7bcfb5e160739079/lib/Translate.php#L240). When you click on “Translate Page” the output should be something like this, where you can check if your Auth Key is correct (your Auth Key is shown after `string(39)`). Your Auth Key should be ending with `:fx` (because you are using the free API).

![Screenshot of debug message from Kirby Panel](https://github.com/tobiasfabian/kirby-machine-translation/assets/1524319/56f0b47c-6ad9-44e9-8f36-119ff4e90905)

https://github.com/tobiasfabian/kirby-machine-translation/blob/d131a65edf0b6824ecf0da8f7bcfb5e160739079/lib/Translate.php#L239-L241

**Comment by andreasba** [comment]
![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/73c5f365-2859-4c7a-bdc8-144c0fcbbf66)

Outputs

`string(39) "59ecab18-xxxx-431e-1bcc-9999c7a6e959:fx"` (I have changed the key a bit and changed it meanwhile - but it is my authkey)

I am running on Kirby 4 alpha-5. Also I have two other plugins active (an SEO one and one for Matomo) but I cannot see how this could impact anything?

When replacing the version of your code, I deleted the whole directory and reuploaded the whole thing.

Oh I also deleted the media directory.

When I don't die(), I get a strange redirect which you obviously do not get.

What Kirby version are you running?

Edit: Interesting. I tried to create a new DeepL authkey and the portal says "Permission denied". So maybe it really is just my key. Let me check with DeepL support.

**Comment by tobiasfabian** [comment]
To debug, you can use a curl command with your Auth Key.

```curl
curl -X POST 'https://api-free.deepl.com/v2/translate' \
--header 'Authorization: DeepL-Auth-Key [yourAuthKey]' \
--header 'Content-Type: application/json' \
--data '{
  "text": [
    "Hello, world!"
  ],
  "target_lang": "DE"
}'
```

https://www.deepl.com/de/docs-api/translate-text/translate-text/

**Comment by andreasba** [comment]
Good idea @tobiasfabian - I get a 403 Forbidden error. Lets wait what DeepL support says.

**Comment by andreasba** [comment]
It works now @tobiasfabian, lots of thanks for your great support! It seems like my account was half-registered half-not-registered, After DeepL support fixed something, I had to re-register, re-generate a new AuthKey and now it works. I will test over the weekend and provide feedback if you like. Danke nochmal!
